version: "3"
services:
    
    notebook:
      image: jupyter/scipy-notebook
      container_name: notebook
      ports:
          - "8888:8888"
      volumes:
          - "./src:/home/jovyan/work"
      command: start-notebook.sh --NotebookApp.token=''